spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microblog-postgres
    username: postgres
    password: postgres

server:
  port: 8081
  error:
   include-stacktrace: never